### ISSUE TITLE
The WSN design tool is not working at all

### ISSUE THREAD

**Issue by rosensilva** [aselaDasanayaka/wsn-design-studio#4]
Hi Asela,
Why is this wsn design tool is not working? Please give a quick response.

Thanks and Regards,
Rosen Silva

**Comment by aselarbd** [comment]
Hi Rosen,
I think you should backend development guy

Thanks and Regards

**Comment by rosensilva** [comment]
no that was Nadith I guess @NadithM. I was the Documentation guy :P
